name: $(Build.SourceBranchName)_$(Build.Reason)_$(majorVersion).$(Build.BuildId)$(Rev:.r)

variables:
  majorVersion: 1.0.0
  buildConfiguration: 'Release'

jobs:
- job: test_runner
  displayName: Run tests
  timeoutInMinutes: 60
  pool:
    name: Default
  steps:
  - template: azure-pipeline-tests.yaml
